### ISSUE TITLE
Missing mods count always starts at the total count of a mod pack. 

### ISSUE THREAD

**Issue by phinocio** [metherul/Automaton#45]
When loading a mod pack and some mods are already installed, the count will still start at the total count of mods in the mod pack. 

Example, I load a modpack containing 13 mods, but I have already downloaded a few. It will show 13 missing instead of the actual missing 5 (in this example pic). When a mod is found/downloaded, it decrements by 1 correctly. IE: If I find 4 of them, it will show 9 as missing, but only 1 file is shown in the app. 

![bug](https://user-images.githubusercontent.com/25400184/55665701-01316b80-57f9-11e9-9ff4-e0cfe858e442.png)

**Comment by metherul** [comment]
Removed. Off topic. Fix it urself, lazy.

**Comment by metherul** [comment]
Kidding. I know why this happened, I'm a moron ;)

**Comment by metherul** [comment]
Fixeronied.
