### ISSUE TITLE
My PC has flagged Automaton as a harmful program twice

### ISSUE THREAD

**Issue by MrTubzy456** [metherul/Automaton#57]
Ok so, like the title says my PC has flagged Automaton as a harmful program twice. Not only that but it was flagged by two different programs. 

The programs that flagged it as harmful were Avast and Malwarebytes.

**Comment by metherul** [comment]
Most likely because it self-extracts the 7z.dll from itself on runtime. Not really something that can be currently fixed until the application becomes signed.
