### ISSUE TITLE
NEW ISSUE dragging with middle mouse crashes automaton

### ISSUE THREAD

**Issue by Hellzbellz123** [metherul/Automaton#63]
if you click the middle mouse button and movethe mount the application will crash
![image](https://user-images.githubusercontent.com/31550512/56132343-95f54100-5f3e-11e9-9d3d-8a17394d72f8.png)

**Comment by metherul** [comment]
Dammit, I swore I fixed this. Slapped it the tracker *again*.

**Comment by Hellzbellz123** [comment]
lmao same. it also seems that if you tab back it will crash sometimes, im not sure why tho

**Comment by metherul** [comment]
Fixed with release v1.3.5.0b.
