### ISSUE TITLE
Fatal Error: Unable to find an entry point named 'GetWindowDpiAwarenessContext' in DLL 'user32.dll'.

### ISSUE THREAD

**Issue by ceide01** [metherul/Automaton#67]
This error showed up. I'm running the newest version and I've never used it before, so I'm guessing this is a problem on my end. Any idea how I can fix it?

**Comment by Karandra** [comment]
This function is only available since Windows 10, version 1607. You seems to be running Automaton on Windows 7, 8 or 8.1.

**Comment by metherul** [comment]
Automaton *should* run fine on Windows 7+. Do you use any custom themes @ceide01?

**Comment by metoonub** [comment]
Hi there! I'm encountering the same error message as Ceide01. 
Using Win 8.1 Pro and just set my theme to Windows Default. 

Additional info:
Following the installation instructions for UltimateSkyrim, I updated to the newest version of .NET (4.8 released on 4/18). I noticed Automaton was last updated on 4/14. Mentioning it in case this has anything to do with the error.

**Comment by metherul** [comment]
Post your logs so I can take a look at the platform version. I'm currently investigating in a virtual machine, trying to see what may be causing the crash.

**Comment by metoonub** [comment]
[Automaton_1.3.3.0_4-20-2019 3-22-07 PM.log](https://github.com/metherul/Automaton/files/3100511/Automaton_1.3.3.0_4-20-2019.3-22-07.PM.log)

**Comment by Yeet592** [comment]
Bump i got the same issue.. Windows 7 if it means anything

**Comment by hoshizora-sayo** [comment]
also having this issue on windows 7

**Comment by whorrak** [comment]
Same issue here on Windows 7.

**Comment by metherul** [comment]
Alrighty, I've moved forward on this issue. While I can't *fix* this error from happening, we can choke it out so it doesn't blow up the rest of the application. It'll most likely be included in the next release.

**Comment by Spirit497** [comment]
Same issue on Windows 7, was there a fix released that I'm not seeing?

**Comment by markovthomas** [comment]
Running Windows 8.1, still getting this error. Any workaround?

**Comment by metherul** [comment]
This issue should be fixed in release v1.3.5.0b.
